component = "PRT"
subcomponent = "PRP"
blocknames = [ "options", "dimensions", "packagedata", "period",]
multipkg = false
stress = false
advanced = false
multi = true

[block.options.boundnames]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = ""
description = "keyword to indicate that boundary names may be provided with the list of particle release points."
deprecated = ""

[block.options.print_input]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "print input to listing file"
description = "REPLACE print_input {'{#1}': 'all model stress package'}"
deprecated = ""

[block.options.dev_exit_solve_method]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "exit solve method"
description = "the method for iterative solution of particle exit location and time in the generalized Pollock's method.  0 default, 1 Brent, 2 Chandrupatla.  The default is Brent's method."
deprecated = ""

[block.options.exit_solve_tolerance]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "exit solve tolerance"
description = "the convergence tolerance for iterative solution of particle exit location and time in the generalized Pollock's method.  A value of 0.00001 works well for many problems, but the value that strikes the best balance between accuracy and runtime is problem-dependent."
deprecated = ""

[block.options.local_z]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "whether to use local z coordinates"
description = "indicates that ``zrpt'' defines the local z coordinate of the release point within the cell, with value of 0 at the bottom and 1 at the top of the cell.  If the cell is partially saturated at release time, the top of the cell is considered to be the water table elevation (the head in the cell) rather than the top defined by the user."
deprecated = ""

[block.options.extend_tracking]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "whether to extend tracking beyond the end of the simulation"
description = "indicates that particles should be tracked beyond the end of the simulation's final time step (using that time step's flows) until particles terminate or reach a specified stop time.  By default, particles are terminated at the end of the simulation's final time step."
deprecated = ""

[block.options.track_filerecord]
type = "record track fileout trackfile"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = ""
description = ""
deprecated = ""

[block.options.track]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "track keyword"
description = "keyword to specify that record corresponds to a binary track output file.  Each PRP Package may have a distinct binary track output file."
deprecated = ""

[block.options.fileout]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."
deprecated = ""

[block.options.trackfile]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = true
numeric_index = false
longname = "file keyword"
description = "name of the binary output file to write tracking information."
deprecated = ""

[block.options.trackcsv_filerecord]
type = "record trackcsv fileout trackcsvfile"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = ""
description = ""
deprecated = ""

[block.options.trackcsv]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "track keyword"
description = "keyword to specify that record corresponds to a CSV track output file.  Each PRP Package may have a distinct CSV track output file."
deprecated = ""

[block.options.trackcsvfile]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = true
numeric_index = false
longname = "file keyword"
description = "name of the comma-separated value (CSV) file to write tracking information."
deprecated = ""

[block.options.stoptime]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "stop time"
description = "real value defining the maximum simulation time to which particles in the package can be tracked.  Particles that have not terminated earlier due to another termination condition will terminate when simulation time STOPTIME is reached.  If the last stress period in the simulation consists of more than one time step, particles will not be tracked past the ending time of the last stress period, regardless of STOPTIME.  If the last stress period in the simulation consists of a single time step, it is assumed to be a steady-state stress period, and its ending time will not limit the simulation time to which particles can be tracked.  If STOPTIME and STOPTRAVELTIME are both provided, particles will be stopped if either is reached."
deprecated = ""

[block.options.stoptraveltime]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "stop travel time"
description = "real value defining the maximum travel time over which particles in the model can be tracked.  Particles that have not terminated earlier due to another termination condition will terminate when their travel time reaches STOPTRAVELTIME.  If the last stress period in the simulation consists of more than one time step, particles will not be tracked past the ending time of the last stress period, regardless of STOPTRAVELTIME.  If the last stress period in the simulation consists of a single time step, it is assumed to be a steady-state stress period, and its ending time will not limit the travel time over which particles can be tracked.  If STOPTIME and STOPTRAVELTIME are both provided, particles will be stopped if either is reached."
deprecated = ""

[block.options.stop_at_weak_sink]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "stop at weak sink"
description = "is a text keyword to indicate that a particle is to terminate when it enters a cell that is a weak sink.  By default, particles are allowed to pass though cells that are weak sinks."
deprecated = ""

[block.options.istopzone]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "stop zone number"
description = "integer value defining the stop zone number.  If cells have been assigned IZONE values in the GRIDDATA block, a particle terminates if it enters a cell whose IZONE value matches ISTOPZONE.  An ISTOPZONE value of zero indicates that there is no stop zone.  The default value is zero."
deprecated = ""

[block.options.drape]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "drape"
description = "is a text keyword to indicate that if a particle's release point is in a cell that happens to be inactive at release time, the particle is to be moved to the topmost active cell below it, if any. By default, a particle is not released into the simulation if its release point's cell is inactive at release time."
deprecated = ""

[block.options.release_timesrecord]
type = "record release_times times"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = ""
description = ""
deprecated = ""

[block.options.release_times]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = ""
description = "keyword indicating release times will follow"
deprecated = ""

[block.options.times]
type = "double"
block_variable = false
valid = []
shape = "(unknown)"
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "release times"
description = "times to release, relative to the beginning of the simulation.  RELEASE_TIMES and RELEASE_TIMESFILE are mutually exclusive."
deprecated = ""

[block.options.release_timesfilerecord]
type = "record release_timesfile timesfile"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = ""
description = ""
deprecated = ""

[block.options.release_timesfile]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = ""
description = "keyword indicating release times file name will follow"
deprecated = ""

[block.options.timesfile]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = true
numeric_index = false
longname = "file keyword"
description = "name of the release times file.  RELEASE_TIMES and RELEASE_TIMESFILE are mutually exclusive."
deprecated = ""

[block.options.dev_forceternary]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "force ternary tracking method"
description = "force use of the ternary tracking method regardless of cell type in DISV grids."
deprecated = ""

[block.dimensions.nreleasepts]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "number of particle release points"
description = "is the number of particle release points."
deprecated = ""

[block.packagedata.irptno]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = true
longname = "PRP id number for release point"
description = "integer value that defines the PRP release point number associated with the specified PACKAGEDATA data on the line. IRPTNO must be greater than zero and less than or equal to NRELEASEPTS.  The program will terminate with an error if information for a PRP release point number is specified more than once."
deprecated = ""

[block.packagedata.cellid]
type = "integer"
block_variable = false
valid = []
shape = "(ncelldim)"
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "cell identifier"
description = "REPLACE cellid {}"
deprecated = ""

[block.packagedata.xrpt]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "x coordinate of release point"
description = "real value that defines the x coordinate of the release point in model coordinates.  The (x, y, z) location specified for the release point must lie within the cell that is identified by the specified cellid."
deprecated = ""

[block.packagedata.yrpt]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "y coordinate of release point"
description = "real value that defines the y coordinate of the release point in model coordinates.  The (x, y, z) location specified for the release point must lie within the cell that is identified by the specified cellid."
deprecated = ""

[block.packagedata.zrpt]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "z coordinate of release point"
description = "real value that defines the z coordinate of the release point in model coordinates or, if the LOCAL_Z option is active, in local cell coordinates.  The (x, y, z) location specified for the release point must lie within the cell that is identified by the specified cellid."
deprecated = ""

[block.packagedata.boundname]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "release point name"
description = "name of the particle release point. BOUNDNAME is an ASCII character variable that can contain as many as 40 characters. If BOUNDNAME contains spaces in it, then the entire name must be enclosed within single quotes."
deprecated = ""

[block.packagedata.packagedata]
type = "recarray irptno cellid xrpt yrpt zrpt boundname"
block_variable = false
valid = []
shape = "(nreleasepts)"
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = ""
description = ""
deprecated = ""

[block.period.releasesetting]
type = "keystring all first frequency steps fraction"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = ""
description = "specifies when to release particles within the stress period.  Overrides package-level RELEASETIME option, which applies to all stress periods. By default, RELEASESETTING configures particles for release at the beginning of the specified time steps. For time-offset releases, provide a FRACTION value."
deprecated = ""

[block.period.all]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = ""
description = "keyword to indicate release of particles at the start of all time steps in the period."
deprecated = ""

[block.period.first]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = ""
description = "keyword to indicate release of particles at the start of the first time step in the period. This keyword may be used in conjunction with other keywords to release particles at the start of multiple time steps."
deprecated = ""

[block.period.frequency]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = ""
description = "release particles at the specified time step frequency. This keyword may be used in conjunction with other keywords to release particles at the start of multiple time steps."
deprecated = ""

[block.period.steps]
type = "integer"
block_variable = false
valid = []
shape = "(<nstp)"
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = ""
description = "release particles at the start of each step specified in STEPS. This keyword may be used in conjunction with other keywords to release particles at the start of multiple time steps."
deprecated = ""

[block.period.fraction]
type = "double"
block_variable = false
valid = []
shape = "(<nstp)"
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = ""
description = "release particles after the specified fraction of the time step has elapsed. If FRACTION is not set, particles are released at the start of the specified time step(s). FRACTION must be a single value when used with ALL, FIRST, or FREQUENCY. When used with STEPS, FRACTION may be a single value or an array of the same length as STEPS. If a single FRACTION value is provided with STEPS, the fraction applies to all steps."
deprecated = ""

[block.period.perioddata]
type = "recarray releasesetting"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = ""
description = ""
deprecated = ""
