component = "SIM"
subcomponent = "NAM"
blocknames = [ "options", "timing", "models", "exchanges", "solutiongroup",]
multipkg = false
stress = false
advanced = false

[block.options.continue]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "continue if not converged"
description = "keyword flag to indicate that the simulation should continue even if one or more solutions do not converge."
deprecated = ""

[block.options.nocheck]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "turn off checking"
description = "keyword flag to indicate that the model input check routines should not be called prior to each time step. Checks are performed by default."
deprecated = ""

[block.options.memory_print_option]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "memory print option"
description = "is a flag that controls printing of detailed memory manager usage to the end of the simulation list file.  NONE means do not print detailed information. SUMMARY means print only the total memory for each simulation component. ALL means print information for each variable stored in the memory manager. NONE is default if MEMORY_PRINT_OPTION is not specified."
deprecated = ""

[block.options.maxerrors]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "maximum number of errors"
description = "maximum number of errors that will be stored and printed."
deprecated = ""

[block.options.print_input]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "print input to listing file"
description = "keyword to activate printing of simulation input summaries to the simulation list file (mfsim.lst). With this keyword, input summaries will be written for those packages that support newer input data model routines.  Not all packages are supported yet by the newer input data model routines."
deprecated = ""

[block.options.hpc_filerecord]
type = "record hpc6 filein hpc6_filename"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = ""
description = "hpc record"
deprecated = ""

[block.options.hpc6]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "head keyword"
description = "keyword to specify that record corresponds to a hpc file."
deprecated = ""

[block.options.filein]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."
deprecated = ""

[block.options.hpc6_filename]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = true
numeric_index = false
longname = "file name of time series information"
description = "name of input file to define HPC file settings for the HPC package. See the ``HPC File'' section for instructions for preparing HPC input files."
deprecated = ""

[block.timing.tdis6]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = true
numeric_index = false
longname = "name of tdis input file"
description = "is the name of the Temporal Discretization (TDIS) Input File."
deprecated = ""

[block.models.mtype]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "model type"
description = "is the type of model to add to simulation."
deprecated = ""

[block.models.mfname]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = true
numeric_index = false
longname = "file name for model name file"
description = "is the file name of the model name file."
deprecated = ""

[block.models.mname]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "name of model"
description = "is the user-assigned name of the model.  The model name cannot exceed 16 characters and must not have blanks within the name.  The model name is case insensitive; any lowercase letters are converted and stored as upper case letters."
deprecated = ""

[block.models.models]
type = "recarray mtype mfname mname"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "list of models"
description = "is the list of model types, model name files, and model names."
deprecated = ""

[block.exchanges.exgtype]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "exchange type"
description = "is the exchange type."
deprecated = ""

[block.exchanges.exgfile]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = true
numeric_index = false
longname = "input file for exchange"
description = "is the input file for the exchange."
deprecated = ""

[block.exchanges.exgmnamea]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "name of model A"
description = "is the name of the first model that is part of this exchange."
deprecated = ""

[block.exchanges.exgmnameb]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "name of model B"
description = "is the name of the second model that is part of this exchange."
deprecated = ""

[block.exchanges.exchanges]
type = "recarray exgtype exgfile exgmnamea exgmnameb"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "list of exchanges"
description = "is the list of exchange types, exchange files, and model names."
deprecated = ""

[block.solutiongroup.mxiter]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "maximum solution group iterations"
description = "is the maximum number of outer iterations for this solution group.  The default value is 1.  If there is only one solution in the solution group, then MXITER must be 1."
deprecated = ""

[block.solutiongroup.slntype]
type = "string"
block_variable = false
valid = [ "ims6", "ems6",]
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "type of solution"
description = "is the type of solution.  The Integrated Model Solution (IMS6) and Explicit Model Solution (EMS6) are the only supported options in this version."
deprecated = ""

[block.solutiongroup.slnfname]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = true
numeric_index = false
longname = "file name for solution input"
description = "name of file containing solution input."
deprecated = ""

[block.solutiongroup.slnmnames]
type = "string"
block_variable = false
valid = []
shape = "(:)"
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "array of model names in this solution"
description = "is the array of model names to add to this solution.  The number of model names is determined by the number of model names the user provides on this line."
deprecated = ""

[block.solutiongroup.solutiongroup]
type = "recarray slntype slnfname slnmnames"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "solution type and models in the solution"
description = "is the list of solution types and models in the solution."
deprecated = ""
